sudo: required
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
services:
  - docker

before_install:
  - docker build -t alexisarancibia/docker-react -f Dockerfile.dev .

install:
  - travis_wait 10

script:
  - docker run alexisarancibia/docker-react npm run test -- --coverage
