sudo: required
services:
  - docker

before_install:
  - docker build -t alexisarancibia/docker-react -f Dockerfile.dev .

install: travis_wait

script:
  - docker run alexisarancibia/docker-react npm run test -- --coverage
